import "./globals.css";
import { Open_Sans } from "next/font/google";
import Header from "@/components/Header";
import AuthContext from "@/context/AuthContext";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={openSans.className}>
      <body>
        <AuthContext>
          <header className='w-full sticky top-0 shadow-md p-4'>
            <Header />
          </header>
          <main>
            {/* */}
            {children}
          </main>
        </AuthContext>
        <div id='portal' />
      </body>
    </html>
  );
}
